### ISSUE TITLE
Style Login Page

### ISSUE THREAD

**Issue by epintozzi** [turingschool/tracker-crm-fe#2]
![Image](https://github.com/user-attachments/assets/0b446df0-f72c-4155-afd2-744c3981eb50)

**Comment by DRIF7ER** [comment]
![Image](https://github.com/user-attachments/assets/788a6a92-7bc6-412e-8733-03473feb0dc2)

## Issue Update

   I've gotten the initial login page to a good spot I believe! I'm not married to anything so we can change it up if we feel like. The above photo is what I have on my machine and it will be my initial pull req.

### The Plan

  Basically I was attempting to mimic the feel of the turing.edu site (since this is basically an extension of Turing). I grabbed the font, colors, and some design elements from there while sticking to the style of the reference image.

### Things Added and/or Changed

- Added: small Turing logo png, large Turing photo png
- Added: 'react-app-env.d.ts' file to allow for image imports without TS throwing an error.
- Changed: 'index.html' file to display tab icon logo
- Edited: App.tsx file, Login.tsx file

**Comment by DRIF7ER** [comment]
## Issue Update

   I've added a test spec for the login page and some additional styling to the success and error messages.

### Things Added and/or Changed

- Added: styling on the errorMessage and successMessage states.
- Added: a LoginSpec.cy.js file to the e2e subfolder in the cypress folder.
- Edited: commented out the h1 element in App.tsx, unsure if we need to keep it.
